### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by theRatramnus** [collisionspace/SVGToPKDrawingCLI#1]
Hi,

I would love to use your tool, and thus it would be great if you could add a license to your project.

Thanks in advance,
Ratramnus

**Comment by collisionspace** [comment]
Hi Ratramnus,


Sorry ya originally I had started down the CLI path for this and kept running into that issue you mentioned there so I moved it to a Package without updating the GitHub repro name.  I can’t remember why there is an issue with CLI as it’s been awhile since I looked at it. Ideally this would exist as a CLI tool given the SVG to PKDrawing overhead.



I go into this a bit here:

https://www.youtube.com/live/Cn9aG1Jjj34?feature=share



Ya I can add a license to it, can get it added by Thursday the 2nd.

Thanks

2023年1月31日(火) 午前4:18 theRatramnus ***@***.***>:

**Comment by theRatramnus** [comment]
That would be great, thanks again!
